import { Experience } from "./schema";

export const appliedAiPublic =
  "AppliedAI (Applied AI Corporation Limited) is an Abu Dhabi-headquartered enterprise AI company, founded in 2021, that builds Opus, an agentic process execution platform for regulated industries such as healthcare, insurance, banking, energy, and government. Opus lets business teams discover, build, run, and optimize AI-agent-driven workflows on a visual canvas, with human-in-the-loop review, audit trails, and policy controls. The company describes the platform as model-agnostic, powered by its own Large Work Model and Work Knowledge Graph, and has raised a G42-led Series A and a Mubadala- and Arbor Ventures-led pre-Series B, with McKinsey & Company, G42, and Firstsource among its named partners.";

export const experience = Experience.array().parse([
  {
    id: "appliedai",
    company: "AppliedAI",
    role: "Full-Stack & AI Product Engineer",
    location: "Abu Dhabi, UAE",
    dates: { start: "2025-06", end: null },
    depth: "full",
    summary:
      "Leads engineering on Process Discovery, a real-time collaborative canvas for building AI-agent workflows, in production with clients in insurance, chemicals, and government. Built on Yjs, now a custom conflict-resolution engine to handle scale.",
    impact: [
      "Forked an open-source workflow engine and rewrote it into Opus's workflow-builder canvas: a node-graph editor with an expressions engine, in TypeScript and Vue.",
      "Ships features on the customer-facing surface in Next.js, React, and Zustand.",
      "Builds situation-based AI pipelines across multiple LLM providers and integrates ElevenLabs text-to-speech.",
      "Partners with presales and customer success on technical calls with prospective and existing customers.",
      "Coaches the frontend team on AI tooling and mentors junior and mid-level engineers.",
    ],
    technologies: [
      "Next.js",
      "React",
      "TypeScript",
      "Vue",
      "Zustand",
      "FastAPI",
      "Yjs",
      "LLM APIs",
      "ElevenLabs",
    ],
    lessons: [],
    work: ["process-discovery", "workflow-canvas", "customer-surface"],
  },
  {
    id: "otani-senior",
    company: "Otani Trading FZCO",
    role: "Senior Software Engineer",
    location: "Dubai, UAE",
    dates: { start: "2024-07", end: "2025-02" },
    depth: "60",
    summary:
      "Led project direction and frontend delivery on Flower Meister, a progressive web app for florists, owning requirements, planning, and DevOps.",
    impact: [
      "Owned requirements, planning, hosting, CI/CD, monitoring, and Docker for Flower Meister.",
      "Designed the UI and UX in Figma with shadcn before writing frontend code.",
      "Built the frontend on Vue 3 with a URQL GraphQL client against a Strawberry and Python backend.",
      "Trained YOLO v5 models and used OpenCV for detection and tracking in the product's computer-vision features.",
      "Mentored junior engineers.",
    ],
    technologies: [
      "Vue 3",
      "shadcn",
      "URQL",
      "GraphQL",
      "Strawberry",
      "FastAPI",
      "YOLO v5",
      "OpenCV",
      "Docker",
      "Figma",
    ],
    lessons: [],
    work: ["flower-meister"],
  },
  {
    id: "otani-swe",
    company: "Otani Trading FZCO",
    role: "Software Engineer",
    location: "Dubai, UAE",
    dates: { start: "2023-09", end: "2024-07" },
    depth: "40",
    summary:
      "Embedded with vendor, merchant, and admin user groups on FMI, a large B2B platform, and shipped seven major features.",
    impact: [
      "Shipped seven major features across the vendor, merchant, and admin surfaces of FMI.",
      "Built backend services with FastAPI, Pydantic, and Peewee.",
      "Built a GraphQL layer with Strawberry over DynamoDB on Project Valit.",
      "Built frontend UI in Vue with RadixVue and shadcn.",
      "Tested with Pytest and Cypress.",
    ],
    technologies: [
      "FastAPI",
      "Pydantic",
      "Peewee",
      "Strawberry",
      "DynamoDB",
      "Vue",
      "RadixVue",
      "shadcn",
      "Pytest",
      "Cypress",
    ],
    lessons: [],
    work: ["fmi-platform"],
  },
  {
    id: "riot",
    company: "RIOT by Preowned Collective Portal FZ LLC",
    role: "Junior Software Engineer",
    location: "Dubai, UAE",
    dates: { start: "2019-09", end: "2023-02" },
    depth: "25",
    summary:
      "Led cross-functional features on a customer-facing platform, including three payment gateways and third-party integrations.",
    impact: [
      "Led cross-functional features on a customer-facing platform, including three payment gateways and third-party integrations.",
      "Migrated data from a legacy platform to Node.js and React.",
      "Built Python automation for Google Ads and Analytics.",
    ],
    technologies: ["Node.js", "React", "Python"],
    lessons: [],
    work: ["riot-platform"],
  },
  {
    id: "alucor",
    company: "Alucor Limited",
    role: "Software Development Engineer Intern",
    location: "Dubai, UAE",
    dates: { start: "2019-01", end: "2019-07" },
    depth: "15",
    summary: "Designed and shipped a Django app that replaced an Excel-based workflow.",
    impact: [
      "Designed and shipped a Django app replacing an Excel-based workflow, with REST APIs and LDAP authentication.",
    ],
    technologies: ["Django", "REST", "LDAP"],
    lessons: [],
    work: ["alucor-workflow-app"],
  },
]);
