import { Project } from "./schema";

export const projects = Project.array().parse([
  {
    slug: "process-discovery",
    title: "Process Discovery",
    tagline: "A real-time collaborative canvas for building AI-agent workflows.",
    category: "case-study",
    featured: true,
    order: 1,
    company: "AppliedAI",
    role: "Lead engineer, prototype to production",
    dates: { start: "2025-06", end: null },
    domains: ["ai", "realtime", "interfaces", "python"],
    technologies: ["Next.js", "React", "FastAPI", "LLM APIs", "ElevenLabs", "Yjs → custom engine"],
    confidential: true,
    heroVisual: {
      kind: "diagram",
      src: "/work/process-discovery/hero.svg",
      alt: "Abstract diagram of a real-time collaborative canvas",
    },
    screenshots: [],
    links: {},
    results: [
      "In production with insurance, chemical, and government customers",
      "Output feeds Opus workflow generation directly",
    ],
    sources: ["resume:2026-08 AppliedAI bullets 1,4"],
  },
  {
    slug: "workflow-canvas",
    title: "Opus workflow-builder canvas",
    tagline: "Forked an open-source workflow engine and rewrote it into Opus's node-graph editor",
    category: "case-study",
    featured: true,
    order: 2,
    company: "AppliedAI",
    role: "Lead engineer, fork to rewrite",
    dates: { start: "2025-06", end: null },
    domains: ["interfaces", "ai", "product"],
    technologies: ["TypeScript", "Vue", "node-graph editor", "expressions engine"],
    confidential: true,
    heroVisual: {
      kind: "diagram",
      src: "/work/workflow-canvas/hero.svg",
      alt: "Node-graph editor canvas with connected workflow nodes",
    },
    screenshots: [],
    links: {},
    results: [
      "Replaced the forked engine's UI and runtime with a purpose-built node-graph editor and expressions engine",
      "In production as the workflow-builder canvas inside Opus",
    ],
    sources: ["resume:2026-08 AppliedAI bullet 2"],
  },
  {
    slug: "scamshield",
    title: "ScamShield",
    tagline: "On-device scam and phishing detection for Chrome, Edge, and Brave.",
    category: "product",
    featured: true,
    order: 3,
    role: "Creator and sole maintainer",
    dates: { start: "2026-06", end: null },
    domains: ["ai", "product"],
    technologies: [
      "MV3",
      "service worker",
      "scikit-learn → JSON",
      "dHash",
      "declarativeNetRequest",
      "Playwright",
    ],
    confidential: false,
    heroVisual: {
      kind: "screenshot",
      src: "/work/scamshield/07.png",
      alt: "ScamShield blocking a phishing page in Chrome",
    },
    screenshots: [
      {
        src: "/work/scamshield/01.png",
        alt: "Popup showing a dangerous verdict with the reasons listed",
        caption: "Popup verdict",
      },
      {
        src: "/work/scamshield/02.png",
        alt: "Statistics panel showing blocked threats over time",
        caption: "Statistics",
      },
      {
        src: "/work/scamshield/03.png",
        alt: "In-page rescue banner warning the user before they submit a form",
        caption: "Rescue banner",
      },
      {
        src: "/work/scamshield/04.png",
        alt: "Language picker showing ScamShield's supported locales",
        caption: "Language picker",
      },
      {
        src: "/work/scamshield/05.png",
        alt: "Wallet guard flagging a suspicious token-approval request",
        caption: "Wallet guard",
      },
      {
        src: "/work/scamshield/06.png",
        alt: "QR code scan result showing the decoded destination before the user visits it",
        caption: "QR scan",
      },
      {
        src: "/work/scamshield/07.png",
        alt: "Full-page block screen shown on a confirmed phishing site",
        caption: "Blocked page",
      },
    ],
    links: {
      github: "https://github.com/joelstephen97/scamshield",
      chromeStore: "https://chromewebstore.google.com/detail/fojjjofjimbfoddafoampojopijnlihl",
      live: "https://joelstephen97.github.io/scamshield/",
    },
    results: [
      "903 unit and 138 end-to-end tests",
      "638 KB zipped",
      "Benchmark 2026-09-07: 56% of fresh phishing pages blocked before load, 69% stopped, 0 hard false positives on 86 controls",
    ],
    sources: [
      "scamshield-repo:tests/unit, tests/e2e (2026-09-08 run)",
      "scamshield-repo:dist/scamshield-chrome.zip",
      "scamshield-repo:docs/benchmark.md (2026-09-07 run)",
    ],
  },
  {
    slug: "flower-meister",
    title: "Flower Meister",
    tagline: "A progressive web app for florist workflows, from Figma to production.",
    category: "case-study",
    featured: true,
    order: 4,
    company: "Otani Trading FZCO",
    role: "Led project direction, frontend, and DevOps",
    dates: { start: "2024-07", end: "2025-02" },
    domains: ["cv", "product", "python"],
    technologies: [
      "Vue 3",
      "shadcn",
      "URQL",
      "Strawberry",
      "FastAPI",
      "YOLO v5",
      "OpenCV",
      "Docker",
    ],
    confidential: false,
    heroVisual: {
      kind: "abstract",
      src: "/work/flower-meister/hero.svg",
      alt: "Flower Meister interface concept",
    },
    screenshots: [],
    links: {},
    results: [
      "Delivered the product across UI validation in Figma, the Vue 3 frontend, the Strawberry and FastAPI backend, hosting, CI/CD, monitoring, and Docker",
      "Computer-vision detection and tracking built with trained YOLO v5 models and OpenCV",
    ],
    sources: ["resume:2026-08 Otani Trading Senior Software Engineer bullets 1-5"],
  },
  {
    slug: "fmi-platform",
    title: "FMI",
    tagline: "A large B2B platform for vendor, merchant, and admin workflows.",
    category: "case-study",
    featured: true,
    order: 5,
    company: "Otani Trading FZCO",
    role: "Software engineer, vendor, merchant, and admin surfaces",
    dates: { start: "2023-09", end: "2024-07" },
    domains: ["python", "product"],
    technologies: [
      "FastAPI",
      "Pydantic",
      "Peewee",
      "Strawberry",
      "DynamoDB",
      "Vue",
      "RadixVue",
      "shadcn",
      "Pytest",
      "Cypress",
    ],
    confidential: false,
    heroVisual: {
      kind: "abstract",
      src: "/work/fmi-platform/hero.svg",
      alt: "FMI platform interface concept",
    },
    screenshots: [],
    links: {},
    results: [
      "Shipped seven major features across vendor, merchant, and admin user groups",
      "Built a GraphQL layer with Strawberry over DynamoDB on Project Valit",
    ],
    sources: ["resume:2026-08 Otani Trading Software Engineer bullets 1-4"],
  },
  {
    slug: "soundprint",
    title: "Soundprint",
    tagline: "An AI-curated Spotify playlist generator.",
    category: "archive",
    featured: false,
    order: 6,
    role: "Creator and sole engineer",
    dates: { start: "2026-06", end: null },
    domains: ["ai", "product"],
    technologies: ["Next.js", "Claude API", "Spotify API"],
    confidential: false,
    heroVisual: {
      kind: "abstract",
      src: "/work/soundprint/hero.svg",
      alt: "Soundprint playlist generator concept",
    },
    screenshots: [],
    links: { github: "https://github.com/joelstephen97/spotify-curator" },
    results: ["Built, not yet deployed; in progress"],
    sources: ["repo:github.com/joelstephen97/spotify-curator"],
  },
  {
    slug: "meetingmind",
    title: "MeetingMind",
    tagline: "A note-taking web app for meetings.",
    category: "archive",
    featured: false,
    order: 7,
    role: "Creator and sole engineer",
    dates: { start: "2026-08", end: null },
    domains: ["ai", "product"],
    technologies: ["Next.js", "React"],
    confidential: false,
    heroVisual: {
      kind: "abstract",
      src: "/work/meetingmind/hero.svg",
      alt: "MeetingMind interface concept",
    },
    screenshots: [],
    links: { live: "https://usemeetingmind.vercel.app" },
    results: ["Live, not yet fully working; in progress"],
    sources: ["repo:usemeetingmind.vercel.app"],
  },
  {
    slug: "scamshield-feed",
    title: "ScamShield Feed",
    tagline: "The blocklist pipeline behind ScamShield's hourly hot list.",
    category: "archive",
    featured: false,
    order: 8,
    role: "Creator and sole engineer",
    dates: { start: "2026-08", end: null },
    domains: ["ai", "product"],
    technologies: ["Node.js", "GitHub Actions", "declarativeNetRequest"],
    confidential: false,
    heroVisual: {
      kind: "abstract",
      src: "/work/scamshield-feed/hero.svg",
      alt: "ScamShield feed pipeline concept",
    },
    screenshots: [],
    links: { github: "https://github.com/joelstephen97/scamshield-feed" },
    results: [
      "Hourly threat-list builder with license-audited sources and poisoning guards, feeding ScamShield's block rules",
    ],
    sources: ["scamshield-feed-repo:build.js, .github/workflows/build.yml"],
  },
  {
    slug: "riot-platform",
    title: "RIOT Platform",
    tagline: "A customer-facing e-commerce platform with three payment gateways.",
    category: "archive",
    featured: false,
    order: 9,
    company: "RIOT by Preowned Collective Portal FZ LLC",
    role: "Junior Software Engineer",
    dates: { start: "2019-09", end: "2023-02" },
    domains: ["product", "python"],
    technologies: ["Node.js", "React", "Python"],
    confidential: false,
    heroVisual: {
      kind: "abstract",
      src: "/work/riot-platform/hero.svg",
      alt: "RIOT platform interface concept",
    },
    screenshots: [],
    links: {},
    results: [
      "Led cross-functional features including three payment gateways and third-party integrations",
      "Migrated data from a legacy platform to Node.js and React",
    ],
    sources: ["resume:2026-08 RIOT bullets 1-3"],
  },
  {
    slug: "alucor-workflow-app",
    title: "Alucor Workflow App",
    tagline: "A Django app that replaced an Excel-based workflow.",
    category: "archive",
    featured: false,
    order: 10,
    company: "Alucor Limited",
    role: "Software Development Engineer Intern",
    dates: { start: "2019-01", end: "2019-07" },
    domains: ["python"],
    technologies: ["Django", "REST", "LDAP"],
    confidential: false,
    heroVisual: {
      kind: "abstract",
      src: "/work/alucor-workflow-app/hero.svg",
      alt: "Alucor workflow app interface concept",
    },
    screenshots: [],
    links: {},
    results: [
      "Designed and shipped a Django app replacing an Excel-based workflow, with REST APIs and LDAP authentication",
    ],
    sources: ["resume:2026-08 Alucor bullet 1"],
  },
  {
    slug: "customer-surface",
    title: "Opus customer-facing surface",
    tagline: "The customer-facing surface of Opus, in Next.js, React, and Zustand.",
    category: "archive",
    featured: false,
    order: 11,
    company: "AppliedAI",
    role: "Engineer",
    dates: { start: "2025-06", end: null },
    domains: ["interfaces", "product"],
    technologies: ["Next.js", "React", "Zustand"],
    confidential: true,
    heroVisual: {
      kind: "abstract",
      src: "/work/customer-surface/hero.svg",
      alt: "Customer-facing surface interface concept",
    },
    screenshots: [],
    links: {},
    results: ["Ships customer-facing features on Opus in Next.js, React, and Zustand"],
    sources: ["resume:2026-08 AppliedAI bullet 3"],
  },
]);
