import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import * as prettier from "prettier";

type ColorToken = { $type: string; $value: string };
type ColorTokensJson = { color: Record<string, Record<string, ColorToken>> };

type ScaleLeaf = { $type: string; $value: string | number };
type ScaleThemedLeaf = { $type: string; $value: { dark: string; light: string } };
type ScaleNode = ScaleLeaf | ScaleThemedLeaf | { [key: string]: ScaleNode };
type ScaleTokensJson = Record<string, { [key: string]: ScaleNode }>;

type SemanticLeaf = { $type: string; $value: { dark: string; light: string } };
type SemanticGroup = { [key: string]: SemanticLeaf | SemanticGroup };
type SemanticTokensJson = Record<string, SemanticGroup>;

const colorTokens = JSON.parse(readFileSync("tokens/color.tokens.json", "utf8")) as ColorTokensJson;
const semanticTokens = JSON.parse(
  readFileSync("tokens/semantic.tokens.json", "utf8"),
) as SemanticTokensJson;
const scaleTokens = JSON.parse(readFileSync("tokens/scale.tokens.json", "utf8")) as ScaleTokensJson;

function camelToKebab(key: string): string {
  return key.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}

function byVarName(a: { varName: string }, b: { varName: string }): number {
  return a.varName.localeCompare(b.varName, undefined, { numeric: true });
}

// ---- Primitives (color ramps + non-themed scale values) -> single :root block ----

type Decl = { varName: string; value: string };

const primitives: Decl[] = [];

for (const [ramp, steps] of Object.entries(colorTokens.color)) {
  for (const [step, token] of Object.entries(steps)) {
    primitives.push({ varName: `--color-${ramp}-${step}`, value: token.$value });
  }
}

function isThemedLeaf(node: ScaleNode): node is ScaleThemedLeaf {
  const value = (node as Partial<ScaleThemedLeaf>).$value;
  return typeof value === "object" && value !== null && "dark" in value && "light" in value;
}

function isLeaf(node: ScaleNode): node is ScaleLeaf {
  const value = (node as Partial<ScaleLeaf>).$value;
  return typeof value === "string" || typeof value === "number";
}

for (const [group, entries] of Object.entries(scaleTokens)) {
  if (group === "shadow") continue; // theme-specific; emitted per-theme below
  for (const [key, node] of Object.entries(entries)) {
    if (!isLeaf(node)) continue;
    const kebabKey = camelToKebab(key);
    // scale.border.* holds widths (hairline/strong/focus px); named --border-width-*
    // to avoid colliding with the semantic --border-subtle|default|strong|focus colors.
    const varName = group === "border" ? `--border-width-${kebabKey}` : `--${group}-${kebabKey}`;
    primitives.push({ varName, value: String(node.$value) });
  }
}

primitives.sort(byVarName);

// ---- Semantic tokens (dot-path -> --kebab-path) -> resolved per theme ----

function flatten(
  node: SemanticGroup,
  prefix = "",
  out: Record<string, { dark: string; light: string }> = {},
) {
  for (const [key, value] of Object.entries(node)) {
    const path = prefix ? `${prefix}.${key}` : key;
    if ("$value" in value && typeof (value as SemanticLeaf).$value === "object") {
      out[path] = (value as SemanticLeaf).$value;
    } else {
      flatten(value as SemanticGroup, path, out);
    }
  }
  return out;
}

const flatSemantic: Record<string, { dark: string; light: string }> = {};
for (const [group, entries] of Object.entries(semanticTokens)) {
  flatten(entries, group, flatSemantic);
}

const REF_PATTERN = /^\{(.+)\}$/;

/** Resolve a raw token value ("{color.ramp.step}" or an rgba literal) into a CSS value. */
function toCssValue(raw: string): string {
  const match = raw.match(REF_PATTERN);
  if (match && match[1]) {
    const parts = match[1].split(".");
    const ramp = parts[1];
    const step = parts[2];
    return `var(--color-${ramp}-${step})`;
  }
  return raw;
}

const darkSemantic: Decl[] = [];
const lightSemantic: Decl[] = [];

for (const [path, value] of Object.entries(flatSemantic)) {
  const varName = `--${path.replace(/\./g, "-")}`;
  darkSemantic.push({ varName, value: toCssValue(value.dark) });
  lightSemantic.push({ varName, value: toCssValue(value.light) });
}

// ---- Shadows (theme-specific, literal box-shadow strings) ----

for (const [key, node] of Object.entries(scaleTokens.shadow ?? {})) {
  if (!isThemedLeaf(node)) continue;
  const varName = `--shadow-${camelToKebab(key)}`;
  darkSemantic.push({ varName, value: node.$value.dark });
  lightSemantic.push({ varName, value: node.$value.light });
}

darkSemantic.sort(byVarName);
lightSemantic.sort(byVarName);

// ---- Emit ----

function renderBlock(decls: Decl[], indent = "  "): string {
  return decls.map((d) => `${indent}${d.varName}: ${d.value};`).join("\n");
}

const css = `/* generated by scripts/build-tokens.ts — do not edit */
:root {
${renderBlock(primitives)}
}

:root,
:root[data-theme="dark"] {
${renderBlock(darkSemantic)}
  color-scheme: dark;
}

:root[data-theme="light"] {
${renderBlock(lightSemantic)}
  color-scheme: light;
}
`;

// Format with the repo's Prettier config so the committed, generated file always
// satisfies `pnpm lint` (prettier --check .) without a separate manual pass.
const prettierConfig = (await prettier.resolveConfig("src/styles/tokens.css")) ?? {};
const formatted = await prettier.format(css, {
  ...prettierConfig,
  filepath: "src/styles/tokens.css",
});

mkdirSync("src/styles", { recursive: true });
writeFileSync("src/styles/tokens.css", formatted);
